### PR TITLE
macOS compatibility

### LINKED ISSUE #16: macOS compatibility
So far, I've tried to make the code base macOS compatible by wrapping all Linux specific code or header inclusions with guards: https://github.com/tasts-robots/vulp/pull/15.

The build succeeds with `tools/bazelisk build //...`.

Tests fail, however, when I do `tools/baselisk test //...`. I've attached the logs, but I'm not sure how to interpret them.
[test_fail.log](https://github.com/tasts-robots/vulp/files/11354766/test_fail.log)

### PR DESCRIPTION
**Pull request by ubgk**
This PR aims to make `vulp` compatible with macOS as discussed in [#16](https://github.com/tasts-robots/vulp/issues/16)

### CODE REVIEW

File: observation/sources/Joystick.cpp [hunk 1]
```diff
@@ -14,6 +14,7 @@
  * limitations under the License.
  */
 
+#ifndef __APPLE__
```
Comment (stephane-caron) [inline observation/sources/Joystick.cpp:17]: We should do this selection in the build system rather than in the source file. To do it, you can go to the corresponding BUILD file (here `observation/sources/BUILD`) and do something like:

```

cc_library(
    name = "sources",
    deps = [
        ":cpu_temperature",
        select({
            "//:linux": [":joystick"],
            "@//conditions:default": [],
        }),
    ],
)
```

File: observation/sources/tests/JoystickTest.cpp [hunk 2]
```diff
@@ -14,6 +14,7 @@
  * limitations under the License.
  */
 
+#ifndef __APPLE__
```
Comment (stephane-caron) [inline observation/sources/tests/JoystickTest.cpp:17]: Same here in ``observation/sources/tests/BUILD``.

**Review by stephane-caron — COMMENTED** [review]
One comment about using the build system rather than checking for ``__APPLE__`` in source, LGTM otherwise :+1:

**Comment by boragokbakan** [comment]
The build succeeds with tools/bazelisk build //....

Tests fail, however, when I do tools/baselisk test //.... I've attached the logs, but I'm not sure how to interpret them [test_fail.log](https://github.com/tasts-robots/vulp/files/11354905/test_fail.log)

File: observation/sources/Joystick.cpp (hunk 1 above)
Comment (boragokbakan) [reply observation/sources/Joystick.cpp:17]: Gotcha, will have a look.

Comment (boragokbakan) [reply observation/sources/Joystick.cpp]: I think my last commit fixes both, let me know if it's what you meant

**Comment by stephane-caron** [comment]
> The build succeeds with tools/bazelisk build //....
> 
> Tests fail, however, when I do tools/baselisk test //.... I've attached the logs, but I'm not sure how to interpret them [test_fail.log](https://github.com/tasts-robots/vulp/files/11354905/test_fail.log)

This seems related to ``typed-ast``, which is installed with version < 1.5.0 because the repo uses mypy == 0.800. It is entirely possible your machine is too recent for this old software :)

The mypy version is set in `tools/mypy/version.txt`. We can try updating to a more recent version of mypy to see if recent Mac architectures are supported now.

**Comment by stephane-caron** [comment]
Simpler: let's remove `mypy_integration` :wink:

**Comment by boragokbakan** [comment]
> > The build succeeds with tools/bazelisk build //....
> > Tests fail, however, when I do tools/baselisk test //.... I've attached the logs, but I'm not sure how to interpret them [test_fail.log](https://github.com/tasts-robots/vulp/files/11354905/test_fail.log)
> 
> This seems related to `typed-ast`, which is installed with version < 1.5.0 because the repo uses mypy == 0.800. It is entirely possible your machine is too recent for this old software :)
> 
> The mypy version is set in `tools/mypy/version.txt`. We can try updating to a more recent version of mypy to see if recent Mac architectures are supported now.

Oh OK, fair enough. I didn't think pip was trying to build something! 🤦‍♂️ I'll rebase after your PR's merged, thanks.

**Comment by boragokbakan** [comment]
I suspect this could require non-trivial modifications to some parts of `vulp`. When I run tests now `vulp/spine/tests/spine_interface_test.py` throws an `AttributeError: module 'posix_ipc' has no attribute 'O_RDWR'`:  (cf. [error.log](https://github.com/tasts-robots/vulp/files/11373131/error.log)).

`O_RDWR` is defined between guards [here](https://github.com/mruffalo/posix_ipc/blob/07fdef7dc8b2b47c09d804fce3c256dcc7fc7f3f/posix_ipc_module.c#L2556), so maybe macOS doesn't implement POSIX message queues?

**Comment by stephane-caron** [comment]
> O_RDWR is defined between guards [here](https://github.com/mruffalo/posix_ipc/blob/07fdef7dc8b2b47c09d804fce3c256dcc7fc7f3f/posix_ipc_module.c#L2556), so maybe macOS doesn't implement POSIX message queues?

@boragokbakan This should have been fixed by https://github.com/tasts-robots/vulp/pull/22.

File: spine/tests/SpineTest.cpp [hunk 3]
```diff
@@ -94,8 +94,7 @@ class SpineTest : public ::testing::Test {
 
     params_.cpu = -1;         // no realtime scheduling
     params_.frequency = 400;  // Hz
-    params_.shm_name = std::string("/") + test_info->test_case_name() + "_" +
-                       test_info->name() + "_" + utils::random_string();
+    params_.shm_name = std::string("/") + utils::random_string();
```
Comment (boragokbakan) [inline spine/tests/SpineTest.cpp:97]: Original name exceeds PSHMNAMLEN in macOS, c.f. [https://opensource.apple.com/source/xnu/xnu-1699.22.81/bsd/kern/posix_shm.c.auto.html](here)

Comment (stephane-caron) [reply spine/tests/SpineTest.cpp:97]: Nice catch! :fishing_pole_and_fish:

File: utils/realtime.h [hunk 4]
```diff
@@ -48,13 +57,18 @@ inline void configure_cpu(int cpu) {
...
   constexpr int kPid = 0;  // this thread
   struct sched_param params = {};
   params.sched_priority = priority;
   if (::sched_setscheduler(kPid, SCHED_RR, &params) < 0) {
     throw std::runtime_error(
         "Error setting realtime scheduler, try running as root (use sudo)");
   }
+#else
+  spdlog::warn(
+      "This function has not been implemented for MacOS, doing nothing...");
```
Comment (stephane-caron) [inline utils/realtime.h:70]:
```suggestion
      "[utils::configure_scheduler] This function does nothing on macOS");
```

Writing out the function name for context.

File: utils/realtime.h [hunk 5]
```diff
@@ -30,13 +34,18 @@ namespace vulp::utils {
...
   constexpr int kPid = 0;  // this thread
   cpu_set_t cpuset = {};
   CPU_ZERO(&cpuset);
   CPU_SET(cpu, &cpuset);
   if (::sched_setaffinity(kPid, sizeof(cpu_set_t), &cpuset) < 0) {
     throw std::runtime_error("Error setting CPU affinity");
   }
+#else
+  spdlog::warn(
+      "This function has not been implemented for macOS, doing nothing...");
```
Comment (stephane-caron) [inline utils/realtime.h:47]:
```suggestion
      "[utils::configure_cpu] This function does nothing on macOS");
```

Sorry for the back and forth, I should have done a proper review :sweat_smile:

**Comment by stephane-caron** [comment]
I see how we can make this work. Let me take care of this for the Bullet part :smiley:
